name: Build and Package

on:
  push:
    branches:
      - main  # 触发工作流的分支，可以修改为你的主分支名称

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 提供的 Ubuntu 最新镜像运行

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '^3.10'  # 指定 Python 版本

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # 编译 Python 脚本
    - name: Build executable
      run: |
        pyinstaller --onefile addtitle.py

    # 上传编译产物
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-executable
        path: dist/addtitle

